# Generated by Django 3.1.7 on 2021-03-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashCardsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
    ]
